import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const asset = (name) => readFileSync(resolve(root, 'assets', name)).toString('base64')

const character = `data:image/webp;base64,${asset('yamada-night-shift-character-v1.webp')}`
const background = `data:image/webp;base64,${asset('yamada-night-shift-background-v1.webp')}`

const output = `/**
 * Generated by scripts/embed-assets.mjs. Do not edit by hand.
 * Assets are embedded so the installed skin never contacts a remote host.
 */
export const YAMADA_NIGHT_SHIFT_CHARACTER = '${character}'
export const YAMADA_NIGHT_SHIFT_BACKGROUND = '${background}'

// Compatibility aliases keep the battle-tested reference lifecycle intact:
// the left slot is present for hot-switch tests but hidden by this skin's CSS.
export const YAMADA_NIGHT_SHIFT_MAID_LEFT = YAMADA_NIGHT_SHIFT_CHARACTER
export const YAMADA_NIGHT_SHIFT_MAID_RIGHT = YAMADA_NIGHT_SHIFT_CHARACTER
export const YAMADA_NIGHT_SHIFT_PALACE_DARK = YAMADA_NIGHT_SHIFT_BACKGROUND
export const YAMADA_NIGHT_SHIFT_PALACE_LIGHT = YAMADA_NIGHT_SHIFT_BACKGROUND
`

writeFileSync(resolve(root, 'src/client/background-art.generated.ts'), output)
